name: twitch-vods-generator
environments:
  - production
services:
  - name: twitch-vods-generator
    type: nodejs
    version: 18
    build:
      commands:
        - npm i
        - npm run build
    run:
      commands:
        - npm start